# Generated by Django 4.2.5 on 2023-09-29 19:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=20, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                ("position", models.CharField(max_length=20, verbose_name="Должность")),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название задачи"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новая", "Новая"),
                            ("В работе", "В работе"),
                            ("Закрыта", "Закрыта"),
                        ],
                        default="Новая",
                        max_length=10,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание задачи"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="projects.task",
                        verbose_name="Надзадача",
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="task_and_workers",
                        to="projects.worker",
                        verbose_name="исполнитель задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название проекта"),
                ),
                ("deadline", models.DateField(verbose_name="Срок исполнения")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание проекта"),
                ),
                ("is_done", models.BooleanField()),
                (
                    "chief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_as_chief",
                        to="projects.worker",
                        verbose_name="Руководитель проекта",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="projects",
                        to="projects.task",
                        verbose_name="Задачи проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.task",
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к задаче",
                "verbose_name_plural": "Комментарии к задаче",
                "ordering": ["-pub_date"],
            },
        ),
    ]
