# Generated by Django 4.2.5 on 2023-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Статус проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название проекта"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание задачи"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название задачи"),
        ),
        migrations.AlterField(
            model_name="task",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_and_workers",
                to="projects.worker",
                verbose_name="Исполнитель задачи",
            ),
        ),
    ]
