# Generated by Django 4.2.5 on 2023-09-29 08:27

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_task_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child",
                to="projects.task",
                verbose_name="Надзадача",
            ),
        ),
    ]
